# Outline

Some modules that we will cover before launching into Logistic Regression heads on. 

Modules:
- Visualization
    - Using matplotlib
    - Using seaborn
- Randomization
    - Using numpy.random
- Panda dataframes

Quick test:
- We want to generate n (say 100) points in 2D randomly in a bounding box.
- We want to generate n points in 2D colored in _one of two colors_. 

Let's tackle the first of the above tasks.


## Randomization

For this, we will assume that 

In [2]:
import numpy as np
from numpy import random
a = random.rand(2, 3)
print a

[[ 0.05368723  0.2072955   0.59916297]
 [ 0.44131501  0.30383213  0.655023  ]]


In [5]:
print a.shape

(2, 3)


In [8]:
a[0]

array([ 0.05368723,  0.2072955 ,  0.59916297])

In [9]:
a[1]

array([ 0.44131501,  0.30383213,  0.655023  ])

In [11]:
b = random.randn(2, 3)
print b

[[-2.06540484  1.61599934  0.07844901]
 [ 0.59047839  1.01626035 -0.57564662]]


In [17]:
a = [1, 2, 3]

In [18]:
print type(a), a

<type 'list'> [1, 2, 3]


In [19]:
a = random.permutation(a)

In [20]:
print type(a), a

<type 'numpy.ndarray'> [2 3 1]


In [21]:
coordstest = np.vstack([np.random.uniform(150, 220, 20), 
                        np.random.uniform(150, 220, 20)]).T

In [22]:
coordstest

array([[ 156.80526847,  161.36309176],
       [ 164.65630779,  156.99145135],
       [ 154.20371385,  206.35616125],
       [ 214.98969127,  184.64623257],
       [ 171.42410791,  194.91030759],
       [ 167.473798  ,  206.59652315],
       [ 170.60090406,  196.66143154],
       [ 183.46711541,  199.04226379],
       [ 163.56479935,  168.76322272],
       [ 206.06266525,  183.28440297],
       [ 195.78663533,  179.27063703],
       [ 198.0793477 ,  153.12319686],
       [ 175.35553388,  194.09387279],
       [ 193.16150146,  152.02080009],
       [ 202.15523944,  181.72668476],
       [ 201.65740448,  197.48096305],
       [ 207.54627164,  188.46456492],
       [ 178.71446904,  197.32295554],
       [ 171.77196431,  175.08441385],
       [ 160.13315685,  202.87799643]])

In [26]:
import pandas as pd
individuals = (np.arange(0,200).reshape(-1,1)*np.ones(10).reshape(1,-1)).flatten()
individuals = pd.Series(individuals)

In [27]:
corr = 0.95 
means = [200, 180]
stds = [10, 10]
covs = [[stds[0]**2, stds[0]*stds[1]*corr],[stds[0]*stds[1]*corr, stds[1]**2]]

In [28]:
coords = np.vstack([np.random.multivariate_normal(coordstest[i,:], covs, 200) 
                         for i in range(10)])

In [30]:
import matplotlib.pyplot as plt

In [ ]:
plt.scatter(allCoords['x'], allCoords['y'], c = individuals, 
      s = 40, cmap = 'hot')